# Generated by Django 3.1.5 on 2021-04-06 05:21

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_customer', models.BooleanField(default=False)),
                ('is_financer', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(default=None, max_length=50)),
                ('phone_number', models.CharField(default='9999999999', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='sellnewcar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyname', models.CharField(default=None, max_length=250)),
                ('Contactnumber', models.CharField(default=None, max_length=10)),
                ('Email', models.EmailField(default=None, max_length=50)),
                ('brand', models.CharField(default=None, max_length=250)),
                ('modelname', models.CharField(default=None, max_length=250)),
                ('variant', models.CharField(default=None, max_length=10)),
                ('fueltype', models.CharField(default=None, max_length=10)),
                ('price', models.CharField(default=None, max_length=10)),
                ('address', models.TextField(default=None, max_length=250)),
                ('city', models.CharField(default=None, max_length=25)),
                ('Frontview', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Backview', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Interiorview', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Leftsideview', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Rightsideview', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Financer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('CompanyName', models.CharField(default='abc', max_length=50)),
                ('interest_rate', models.CharField(max_length=100)),
                ('Address', models.CharField(default='Enter Address Here', max_length=200)),
                ('City', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='sellcar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ownername', models.CharField(default=None, max_length=250)),
                ('Contactnumber', models.CharField(default=None, max_length=10)),
                ('Email', models.EmailField(default=None, max_length=50)),
                ('brand', models.CharField(default=None, max_length=250)),
                ('modelname', models.CharField(default=None, max_length=250)),
                ('yearofmanufacture', models.CharField(default=None, max_length=4)),
                ('kilometersdone', models.CharField(default=None, max_length=6)),
                ('fueltype', models.CharField(default=None, max_length=10)),
                ('noofowners', models.CharField(default=None, max_length=2)),
                ('price', models.CharField(default=None, max_length=10)),
                ('city', models.CharField(default=None, max_length=25)),
                ('Frontview', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Backview', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Interiorview', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Leftsideview', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Rightsideview', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='favvv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sellnewcar')),
            ],
        ),
        migrations.CreateModel(
            name='favv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sellcar')),
            ],
        ),
        migrations.CreateModel(
            name='finreq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=250)),
                ('middlename', models.CharField(default=None, max_length=250)),
                ('lastname', models.CharField(default=None, max_length=250)),
                ('contactnumber', models.CharField(default=None, max_length=10)),
                ('email', models.EmailField(default=None, max_length=50)),
                ('dateofb', models.DateField(default=datetime.date.today)),
                ('maritalstatus', models.CharField(choices=[('Married', 'MARRIED'), ('Unmarried', 'UNMARRIED')], default='Unmarried', max_length=10)),
                ('address', models.TextField(default=None, max_length=250)),
                ('city', models.CharField(default=None, max_length=25)),
                ('occupation', models.CharField(default=None, max_length=25)),
                ('grossincome', models.CharField(default=None, max_length=10)),
                ('aadharcard', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pancard', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('bankstatement', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('passportsizephoto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ITreturn', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='car_id', to='accounts.sellcar')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financer_id', to='accounts.financer')),
            ],
        ),
    ]
