# Generated by Django 3.1.5 on 2021-02-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financer',
            old_name='location',
            new_name='City',
        ),
        migrations.AddField(
            model_name='financer',
            name='Address',
            field=models.TextField(default='Enter Address Here', max_length=200),
        ),
        migrations.AddField(
            model_name='financer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
