# Generated by Django 3.1.5 on 2021-02-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210215_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='financer',
            name='CompanyName',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
