# Generated by Django 3.1.5 on 2021-02-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_finreq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finreq',
            old_name='lasttname',
            new_name='lastname',
        ),
    ]
