# Generated by Django 3.1.5 on 2021-02-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_finreq_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finreq',
            name='maritalstatus',
            field=models.CharField(choices=[('Married', 'MARRIED'), ('Unmarried', 'UNMARRIED')], default='Unmarried', max_length=10),
        ),
    ]
