# Generated by Django 3.1.5 on 2021-02-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210216_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellcar',
            name='Contactnumber',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
