# Generated by Django 3.1.5 on 2021-02-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210225_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellcar',
            name='Email',
            field=models.EmailField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='Ownername',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='brand',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='city',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='fueltype',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='kilometersdone',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='modelname',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='noofowners',
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='price',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='yearofmanufacture',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
