# Generated by Django 3.1.5 on 2021-03-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_sellcar_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellcar',
            name='isfav',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
