# Generated by Django 3.1.5 on 2021-03-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_sellcar_isfav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellcar',
            name='isfav',
        ),
    ]
