# Generated by Django 3.1.5 on 2021-03-05 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_favvv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='favvv',
        ),
    ]
