# Generated by Django 3.1.5 on 2021-03-08 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_sellnewcar_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellnewcar',
            name='user_id',
        ),
        migrations.AddField(
            model_name='sellcar',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='accounts.customer'),
        ),
    ]
