# Generated by Django 3.1.5 on 2021-03-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210308_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellcar',
            name='user_id',
        ),
    ]
